# Generated by Django 5.1.1 on 2024-09-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.PositiveIntegerField()),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_description', models.TextField(max_length=200)),
                ('product_stock', models.PositiveIntegerField()),
                ('sales_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
